name: DropGaussian
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip=25.0
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0=cuda
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tqdm
  - numpy<2
  - mkl<2024.1
  - pip:
    - plyfile
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - matplotlib
    - torchmetrics==1.2.0
    - opencv_python
    - scipy
    - numpy<2